/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author khadamikhwan
 */
import java.awt.HeadlessException;
import java.io.File;
import utility.KoneksiDB;
import java.sql.*;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

public class HistoryRental extends javax.swing.JFrame {

    public Statement st;
    public ResultSet rs;
    Connection konek = KoneksiDB.BuatKoneksi();
    private DefaultTableModel tabmode;
    private DefaultTableModel tabmode2;

    /**
     * Creates HistoryRental
     */
    public HistoryRental() {
        initComponents();
        datatable2();
        Clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_keluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_cetak = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo-safa-long.png"))); // NOI18N

        btn_keluar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btn_keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setText("Riwayat Sewa");

        btn_cetak.setText("Cetak");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Rental", "Pelanggan", "Tanggal sewa", "Lama sewa", "Total ", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.getTableHeader().setReorderingAllowed(false);
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_keluar, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addGap(210, 210, 210)
                                .addComponent(btn_cetak, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                .addGap(199, 199, 199)
                                .addComponent(btn_batal, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void datatable() {
        Object[] Baris = {"ID Pelanggan", "Nama depan", "Nama Belakang", "Alamat", "Kota", "No Telepon"};
        tabmode = new DefaultTableModel(null, Baris);
        try {
            String query = "SELECT * FROM customers";

            Statement stat = konek.createStatement();
            ResultSet hasil = stat.executeQuery(query);

            while (hasil.next()) {
                tabmode.addRow(new Object[]{
                    "PLG_" + hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6),});
            }
            tabel.setModel(tabmode);
        } catch (Exception e) {
            System.out.println("erorr: " + e);
        }
    }

    protected void datatable2() {
        Object[] Baris = {"ID Rental", "Nama Customer", "Tanggal Sewa", "Lama sewa", "Total Harga", "Status", "Jumlah Item"};
        tabmode2 = new DefaultTableModel(null, Baris);
        try {

            String query = "SELECT\n"
                    + "    r.id_rental,\n"
                    + "    c.nama_depan,\n"
                    + "    c.nama_belakang,\n"
                    + "    r.created_at,\n"
                    + "    r.rental_days,\n"
                    + "    r.total_price,\n"
                    + "    r.status,\n"
                    + "    COUNT(ir.id_rental) AS item_count\n"
                    + "FROM\n"
                    + "    rentals r\n"
                    + "JOIN\n"
                    + "    customers c ON c.id_customer = r.id_customer\n"
                    + "LEFT JOIN\n"
                    + "    item_rentals ir ON r.id_rental = ir.id_rental\n"
                    + "GROUP BY\n"
                    + "    r.id_rental, c.nama_depan, c.nama_belakang, r.created_at, r.rental_days, r.total_price, r.status\n";

            PreparedStatement stat = konek.prepareStatement(query);

            ResultSet hasil = stat.executeQuery();

            while (hasil.next()) {
                tabmode2.addRow(new Object[]{
                    "RTL_" + hasil.getString(1),
                    hasil.getString(2) + " " + hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6),
                    hasil.getString(7),
                    hasil.getString(8),});
            }

            tabel.setModel(tabmode2);
        } catch (Exception e) {
            System.out.println("erorr: " + e);
        }
    }

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        MainScreen mainScreen = new MainScreen();
        mainScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        Clear();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_batalActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
//        int selectedRow = tabel.getSelectedRow();
//        if (selectedRow != -1) {
//            System.out.print("tabelMouseClicked" + tabel.getValueAt(selectedRow, 0).toString());
//            System.out.print("regex" + tabel.getValueAt(selectedRow, 0).toString().replaceAll("[^0-9]", ""));
//            datatable2(tabel.getValueAt(selectedRow, 0).toString().replaceAll("[^0-9]", ""));
//
//            btn_add.setEnabled(false);
//            btn_batal.setEnabled(true);
//            btn_edit.setEnabled(true);
//            btn_delete.setEnabled(true);
//
//            selectionCustomer.setSelectedIndex(helper.updateComboBoxSelection(selectionCustomer, tabel.getValueAt(selectedRow, 1).toString()));
//            txt_days.setText(tabel.getValueAt(selectedRow, 2).toString());
//            txt_length.setText(tabel.getValueAt(selectedRow, 3).toString());
//            txt_total.setText(tabel.getValueAt(selectedRow, 4).toString());
//            //            selectionStatus.setSelectedIndex(helper.updateComboBoxSelection(selectionStatus, tabel.getValueAt(selectedRow, 5).toString()));
//        }
    }//GEN-LAST:event_tabelMouseClicked

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        File reportFile = new File(".");
        try {
            JasperDesign design = JRXmlLoader.load(reportFile.getCanonicalPath() + "/src/dataReport/" + "Tesreport.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(design);

            String query = "SELECT\n"
                    + "    r.id_rental,\n"
                    + "    c.nama_depan,\n"
                    + "    c.nama_belakang,\n"
                    + "    r.created_at,\n"
                    + "    r.rental_days,\n"
                    + "    r.total_price,\n"
                    + "    r.status,\n"
                    + "    COUNT(ir.id_rental) AS item_count\n"
                    + "FROM\n"
                    + "    rentals r\n"
                    + "JOIN\n"
                    + "    customers c ON c.id_customer = r.id_customer\n"
                    + "LEFT JOIN\n"
                    + "    item_rentals ir ON r.id_rental = ir.id_rental\n"
                    + "GROUP BY\n"
                    + "    r.id_rental, c.nama_depan, c.nama_belakang, r.created_at, r.rental_days, r.total_price, r.status\n";

            PreparedStatement stat = konek.prepareStatement(query);

            ResultSet hasil = stat.executeQuery();

            JRResultSetDataSource rsDataSource = new JRResultSetDataSource(hasil);
            JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap(), rsDataSource);
            JasperViewer.viewReport(jp);


        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Error cetak", "error", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void Clear() {
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoryRental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
