/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author khadamikhwan
 */
import java.awt.HeadlessException;
import utility.KoneksiDB;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManageCustomer extends javax.swing.JFrame {

    public Statement st;
    public ResultSet rs;
    Connection konek = KoneksiDB.BuatKoneksi();
    private DefaultTableModel tabmode;
    private DefaultTableModel tabmode2;

    /**
     * Creates ManageCustomer
     */
    public ManageCustomer() {
        initComponents();
        datatable();
        Clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        btn_keluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_nama_depan = new javax.swing.JTextField();
        txt_nama_belakang = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        clear_id = new javax.swing.JButton();
        clear_password = new javax.swing.JButton();
        txt_kota = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        clear_nama = new javax.swing.JButton();
        clear_alamat = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        txt_telepon = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        clear_alamat1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo-safa-long.png"))); // NOI18N

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Pelanggan", "Nama depan", "Nama Belakang", "Alamat", "Kota", "Telepon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.getTableHeader().setReorderingAllowed(false);
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);
        if (tabel.getColumnModel().getColumnCount() > 0) {
            tabel.getColumnModel().getColumn(0).setResizable(false);
            tabel.getColumnModel().getColumn(1).setResizable(false);
            tabel.getColumnModel().getColumn(2).setResizable(false);
            tabel.getColumnModel().getColumn(3).setResizable(false);
            tabel.getColumnModel().getColumn(4).setResizable(false);
            tabel.getColumnModel().getColumn(5).setResizable(false);
        }

        btn_keluar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btn_keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setText("Management Pelanggan");

        btn_add.setText("Tambah Data");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit Data");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_delete.setText("Hapus Data");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        jLabel8.setText("Nama Depan");

        txt_nama_depan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_depanActionPerformed(evt);
            }
        });

        txt_nama_belakang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_belakangActionPerformed(evt);
            }
        });

        jLabel11.setText("Nama belakang");

        clear_id.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/x.png"))); // NOI18N
        clear_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_idActionPerformed(evt);
            }
        });

        clear_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/x.png"))); // NOI18N
        clear_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_passwordActionPerformed(evt);
            }
        });

        txt_kota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kotaActionPerformed(evt);
            }
        });

        jLabel12.setText("Kota");

        clear_nama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/x.png"))); // NOI18N
        clear_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_namaActionPerformed(evt);
            }
        });

        clear_alamat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/x.png"))); // NOI18N
        clear_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_alamatActionPerformed(evt);
            }
        });

        jLabel9.setText("Alamat");

        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });

        txt_telepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_teleponActionPerformed(evt);
            }
        });

        jLabel13.setText("Telepon");

        clear_alamat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/x.png"))); // NOI18N
        clear_alamat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_alamat1ActionPerformed(evt);
            }
        });

        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Rental", "Pelanggan", "Tanggal sewa", "Lama sewa", "Total ", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel1.getTableHeader().setReorderingAllowed(false);
        tabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel1);

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setText("Riwayat Sewa Pelanggan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_batal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel8))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txt_nama_depan, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(clear_id))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txt_nama_belakang, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(clear_password))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel12)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(clear_nama))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txt_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(clear_alamat)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clear_alamat1)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clear_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_nama_depan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clear_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_nama_belakang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clear_nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clear_alamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clear_alamat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void datatable() {
        Object[] Baris = {"ID Pelanggan", "Nama depan", "Nama Belakang", "Alamat", "Kota", "No Telepon"};
        tabmode = new DefaultTableModel(null, Baris);
        try {
            String query = "SELECT * FROM customers";

            Statement stat = konek.createStatement();
            ResultSet hasil = stat.executeQuery(query);

            while (hasil.next()) {
                tabmode.addRow(new Object[]{
                    "PLG_" + hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6),});
            }
            tabel.setModel(tabmode);
        } catch (Exception e) {
            System.out.println("erorr: " + e);
        }
    }

    protected void datatable2(String id) {
        Object[] Baris = {"ID Rental", "Nama Customer", "Tanggal Sewa", "Lama sewa", "Total Harga", "Status"};
        tabmode2 = new DefaultTableModel(null, Baris);
        try {

            String query = "SELECT\n"
                    + "    r.id_rental,\n"
                    + "    c.nama_depan,\n"
                    + "    c.nama_belakang,\n"
                    + "    r.created_at,\n"
                    + "    r.rental_days,\n"
                    + "    r.total_price,\n"
                    + "    r.status \n"
                    + "FROM\n"
                    + "    rentals r\n"
                    + "JOIN\n"
                    + "    customers c ON c.id_customer = r.id_customer\n"
                    + "WHERE r.id_customer = ?";

//            Statement stat = konek.createStatement();
//            ResultSet hasil = stat.executeQuery(query);
            PreparedStatement stat = konek.prepareStatement(query);

            stat.setString(1, id);

            ResultSet hasil = stat.executeQuery();

            while (hasil.next()) {
                tabmode2.addRow(new Object[]{
                    "RTL_" + hasil.getString(1),
                    hasil.getString(2) + " " + hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6),
                    hasil.getString(7),});
            }

            tabel1.setModel(tabmode2);
        } catch (Exception e) {
            System.out.println("erorr: " + e);
        }
    }

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        MainScreen mainScreen = new MainScreen();
        mainScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        if (txt_nama_depan.getText().equals("") || txt_nama_belakang.getText().equals("") || txt_alamat.getText().equals("") || txt_kota.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Data harus di isi semua", "error", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                String sql = "insert into customers values (?,?,?,?,?,?)";
                PreparedStatement stat = konek.prepareStatement(sql);
                stat.setString(1, null);
                stat.setString(2, txt_nama_depan.getText());
                stat.setString(3, txt_nama_belakang.getText());
                stat.setString(4, txt_alamat.getText());
                stat.setString(5, txt_kota.getText());
                stat.setString(6, txt_telepon.getText());
                stat.executeUpdate();

                JOptionPane.showMessageDialog(null, "Berhasil tambah data", "success", JOptionPane.INFORMATION_MESSAGE);
                datatable();
            } catch (Exception e) {
                System.out.println("erorr: btn_addActionPerformed " + e);
            }
            Clear();
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void txt_nama_depanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_depanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_depanActionPerformed

    private void txt_nama_belakangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_belakangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_belakangActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int selectedRow = tabel.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a row to delete.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        System.out.println("selectedRow " + selectedRow);

        int ok = JOptionPane.showConfirmDialog(null, "yakin hapus data ini?", "konfirmasi dialog", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {

            try {
                String selectedId = tabel.getValueAt(selectedRow, 0).toString().substring(4);
                String sql = "delete from customers where id_customer ='" + selectedId + "'";
                PreparedStatement stat = konek.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Berhasil menghapus " + tabel.getValueAt(selectedRow, 0).toString() + " " + tabel.getValueAt(selectedRow, 1).toString(), "success", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e, "error", JOptionPane.INFORMATION_MESSAGE);
            }
            datatable();
            Clear();

        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void clear_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_idActionPerformed
        // TODO add your handling code here:
        txt_nama_depan.setText("");
    }//GEN-LAST:event_clear_idActionPerformed

    private void clear_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_passwordActionPerformed
        // TODO add your handling code here:
        txt_nama_belakang.setText("");
    }//GEN-LAST:event_clear_passwordActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        int selectedRow = tabel.getSelectedRow();
        if (selectedRow != -1) {
            System.out.print(tabel.getValueAt(selectedRow, 0).toString().replaceAll("[^0-9]", ""));

            btn_add.setEnabled(false);
            btn_batal.setEnabled(true);
            btn_edit.setEnabled(true);
            btn_delete.setEnabled(true);

            txt_nama_depan.setText(tabel.getValueAt(selectedRow, 1).toString());
            txt_nama_belakang.setText(tabel.getValueAt(selectedRow, 2).toString());
            txt_alamat.setText(tabel.getValueAt(selectedRow, 3).toString());
            txt_kota.setText(tabel.getValueAt(selectedRow, 4).toString());
            txt_telepon.setText(tabel.getValueAt(selectedRow, 5).toString());
            datatable2(tabel.getValueAt(selectedRow, 0).toString().replaceAll("[^0-9]", ""));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tabelMouseClicked

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        try {
            int selectedRow = tabel.getSelectedRow();
            String idBarang = tabel.getValueAt(selectedRow, 0).toString().substring(4);
            // Construct the SQL update query
            String sql = "UPDATE customers "
                    + "SET "
                    + "nama_depan = ? ,"
                    + "nama_belakang = ? ,"
                    + "alamat = ? ,"
                    + "kota = ? ,"
                    + "telepon = ? "
                    + "WHERE id_customer = ?";

            PreparedStatement stat = konek.prepareStatement(sql);
            stat.setString(1, txt_nama_depan.getText());
            stat.setString(2, txt_nama_belakang.getText());
            stat.setString(3, txt_alamat.getText());
            stat.setString(4, txt_kota.getText());
            stat.setString(5, txt_telepon.getText());
            stat.setString(6, idBarang);

            // Execute the update query
            int rowsAffected = stat.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Berhasil update data", "success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Gagal update data", "error", JOptionPane.ERROR_MESSAGE);
            }
            datatable();
            Clear();
        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Error update data", "error", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        Clear();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_batalActionPerformed

    private void txt_kotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kotaActionPerformed

    private void clear_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_namaActionPerformed

    private void clear_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_alamatActionPerformed

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void txt_teleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_teleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_teleponActionPerformed

    private void clear_alamat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_alamat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_alamat1ActionPerformed

    private void tabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel1MouseClicked
        // TODO add your handling code here:
//        int selectedRow = tabel.getSelectedRow();
//        if (selectedRow != -1) {
//            System.out.print("tabelMouseClicked" + tabel.getValueAt(selectedRow, 0).toString());
//            System.out.print("regex" + tabel.getValueAt(selectedRow, 0).toString().replaceAll("[^0-9]", ""));
//            datatable2(tabel.getValueAt(selectedRow, 0).toString().replaceAll("[^0-9]", ""));
//
//            btn_add.setEnabled(false);
//            btn_batal.setEnabled(true);
//            btn_edit.setEnabled(true);
//            btn_delete.setEnabled(true);
//
//            selectionCustomer.setSelectedIndex(helper.updateComboBoxSelection(selectionCustomer, tabel.getValueAt(selectedRow, 1).toString()));
//            txt_days.setText(tabel.getValueAt(selectedRow, 2).toString());
//            txt_length.setText(tabel.getValueAt(selectedRow, 3).toString());
//            txt_total.setText(tabel.getValueAt(selectedRow, 4).toString());
//            //            selectionStatus.setSelectedIndex(helper.updateComboBoxSelection(selectionStatus, tabel.getValueAt(selectedRow, 5).toString()));
//        }
    }//GEN-LAST:event_tabel1MouseClicked

    private void Clear() {
        if (tabmode2 != null) {
            tabmode2.setRowCount(0); // Removes all rows from the table
        }
        txt_nama_belakang.setText("");
        txt_nama_depan.setText("");
        txt_alamat.setText("");
        txt_kota.setText("");
        txt_telepon.setText("");
        btn_add.setEnabled(true);
        btn_batal.setEnabled(false);
        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton clear_alamat;
    private javax.swing.JButton clear_alamat1;
    private javax.swing.JButton clear_id;
    private javax.swing.JButton clear_nama;
    private javax.swing.JButton clear_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabel;
    private javax.swing.JTable tabel1;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_kota;
    private javax.swing.JTextField txt_nama_belakang;
    private javax.swing.JTextField txt_nama_depan;
    private javax.swing.JTextField txt_telepon;
    // End of variables declaration//GEN-END:variables
}
